import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // `src/kernel/pkg` is wasm-bindgen's output, generated by the kernel's
  // `tools/build-wasm.sh` and gitignored. CI builds it and would then lint it
  // on every run; nobody can act on what it says.
  globalIgnores(['dist', 'src/kernel/pkg']),
  {
    files: ['**/*.{js,jsx}'],
    extends: [
      js.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
      parserOptions: {
        ecmaVersion: 'latest',
        ecmaFeatures: { jsx: true },
        sourceType: 'module',
      },
    },
    rules: {
      // `varsIgnorePattern` is here because this config has no
      // `eslint-plugin-react`, so `<Foo />` does not count as a use of `Foo`
      // and every component import would be flagged. `argsIgnorePattern` is
      // the same exemption for a component arriving as a parameter — a
      // destructured `{ Icon }` rendered as `<Icon />` is used, and only the
      // JSX blindness says otherwise.
      //
      // `ignoreRestSiblings` allows the destructure-to-omit idiom,
      // `const { tier, ...withoutTier } = design`, where naming the field is
      // the whole point of the line.
      'no-unused-vars': ['error', {
        varsIgnorePattern: '^[A-Z_]',
        argsIgnorePattern: '^[A-Z_]',
        ignoreRestSiblings: true,
      }],
    },
  },
  {
    // The Playwright suite and its config run in the test runner, not in the
    // browser: `Buffer` and `process` are node globals there.
    files: ['e2e/**/*.js', 'playwright.config.js'],
    languageOptions: { globals: globals.node },
  },
  {
    // The kernel loader runs in both, and says so: it branches on
    // `typeof process !== 'undefined'` because vitest has to read the wasm off
    // disk where the browser fetches it. The guard is the point of the line.
    files: ['src/kernel/index.js'],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
  },
])
